[tool.black]
line-length = 100

[tool.isort]
profile = "black"

[tool.mypy]
python_version = "3.9"
warn_unused_configs = true
warn_unreachable = true
warn_no_return = true
warn_unused_ignores = true
ignore_missing_imports = true
