name: Run CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  tox:
    name: Run Tox
    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install gcc python3.9 python3-dev libkrb5-dev krb5-user
        sudo ln -s /usr/lib/x86_64-linux-gnu/libgssapi_krb5.so.2 /usr/lib/libgssapi_krb5.so
    - name: Run all envs
      uses: fedora-python/tox-github-action@master
      with:
        tox_env: ${{ matrix.tox_env }}
    strategy:
      matrix:
        tox_env: [black, isort, flake8]
    runs-on: ubuntu-latest